let campeones = [
    { id: '1', posicion: 'Superior', nombre: 'Aatrox', precio: convertir(880), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg', biografia: 'Aatrox y sus hermanos, que alguna vez fueron respetados defensores de Shurima contra el Vacío, se convirtieron en una amenaza aún mayor para Runaterra y los derrotaron con hechicería mortal usada con astucia. Pero, después de siglos de encarcelamiento, Aatrox fue el primero en encontrar la libertad una vez más; corrompió y transformó a los bastante tontos como para intentar blandir el arma mágica que contenía su esencia. Ahora, con cuerpos robados, camina por Runaterra con una apariencia retorcida de su forma original y busca la venganza apocalíptica que tanto desea.', dificultad: 2 },
    { id: '2', posicion: 'Central', nombre: 'Ahri', precio: convertir(790), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg', biografia: 'Ahri, conectada de forma innata con el poder latente de Runaterra, es una vastaya que puede moldear la magia en orbes de energía pura. Se divierte jugueteando con su presa y manipulando sus emociones, antes de devorar su esencia vital. A pesar de su naturaleza predadora, Ahri conserva cierta empatía porque recibe destellos de los recuerdos de cada alma que consume.', dificultad: 2 },
    { id: '3', posicion: 'Superior, Central', nombre: 'Akali', precio: convertir(790), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg', biografia: 'Tras renunciar a la Orden Kinkou y a su título como el Puño de la Sombra, Akali pelea a solas, lista para ser el arma letal que su pueblo necesita. Aunque conserva todo lo que aprendió de su maestro Shen, juró defender a Jonia de sus enemigos... una víctima a la vez. Puede que Akali ataque en silencio, pero su mensaje resonará con fuerza y claridad: témanle a la asesina sin maestro.', dificultad: 2 },
    { id: '4', posicion: 'Central', nombre: 'Akshan', precio: convertir(975), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akshan_0.jpg', biografia: 'Con una ceja levantada frente al peligro, Akshan pelea contra el mal con un carisma deslumbrante, una venganza justiciera y una llamativa falta de camisas. Con gran habilidad en el arte del combate furtivo, es capaz de evadir a sus enemigos y reaparecer cuando menos se lo esperan. Con un profundo sentido de la justicia y un arma legendaria que desafía a la muerte, corrige las injusticias cometidas por los rufianes de Runaterra mientras se rige por su propio código moral: "No seas un imbécil".', dificultad: 1 },
    { id: '5', posicion: 'Soporte', nombre: 'Alistar', precio: convertir(585), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg', biografia: 'Alistar, que desde siempre fue un gran guerrero con una temible reputación, busca venganza por la muerte de su clan a manos del imperio noxiano. Aunque haya sido esclavizado y forzado a tener una vida de gladiador, su voluntad inquebrantable fue lo que impidió que se convirtiera en una bestia completamente. Ahora, libre de las cadenas de sus anteriores amos, pelea en nombre de los desamparados y desprotegidos usando tanto su furia como sus cuernos, pezuñas y puños como armas.', dificultad: 2 },
    { id: '6', posicion: 'Jungla', nombre: 'Amumu', precio: convertir(260), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg', biografia: 'Cuenta la leyenda que Amumu es un alma solitaria y melancólica de la antigua Shurima que vaga por el mundo en busca de un amigo. Una antigua maldición lo condenó a permanecer solo por toda la eternidad. Sus caricias son la muerte, su afecto es la ruina. Quienes afirman haberlo visto lo describen como un cadáver viviente de corta estatura envuelto en vendajes. Amumu ha sido la inspiración de mitos, canciones y folclore que se han contado una y otra vez a lo largo de generaciones, tanto que es imposible separar la verdad de la ficción.', dificultad: 1 },
    { id: '7', posicion: 'Central', nombre: 'Anivia', precio: convertir(790), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg', biografia: 'Anivia es un espíritu benevolente alado que soporta interminables ciclos de vida, muerte y resurrección para proteger Fréljord. Nació de la unión del hielo cruel y del viento penetrante, por lo que es una semidiosa que utiliza esos poderes elementales para frustrar a quien se atreva a perturbar su tierra natal. Anivia guía y protege a las tribus del norte hostil, quienes la veneran como símbolo de esperanza y como presagio de un gran cambio. Pelea con cada fibra de su ser sabiendo que su recuerdo perdurará a través de su sacrificio y que renacerá en un nuevo mañana.', dificultad: 3 },
    { id: '8', posicion: 'Central', nombre: 'Annie', precio: convertir(260), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg', biografia: 'Annie es una peligrosa, talentosa y encantadora niña maga que posee un inmenso poder piroquinético. Incluso bajo las sombras de las montañas al norte de Noxus, es una maga excepcional. Su afinidad innata con el fuego se manifestó pronto en su vida a través de explosiones emocionales impredecibles, aunque con el tiempo aprendió a controlar esos "trucos". Uno de sus favoritos es invocar a Tibbers, su amado osito de peluche, como una feroz bestia de fuego. Perdida en la perpetua inocencia de la niñez, Annie vaga por los bosques oscuros siempre en busca de alguien con quien jugar.', dificultad: 2 },
    { id: '9', posicion: 'Inferior', nombre: 'Aphelios', precio: convertir(975), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg', biografia: 'Aphelios emerge de la sombra de la luz de la luna con sus armas listas y mata a los enemigos de su fe en un silencio melancólico. Habla únicamente a través de la certeza de su puntería y del disparo de cada arma. Si bien su impulso proviene de un veneno que lo enmudece, es guiado por su hermana Alune. Desde un santuario lejano, le envía un arsenal de armas de piedra lunar a sus manos. Mientras la luna resplandezca en lo alto, Aphelios nunca estará solo.', dificultad: 3 },
    { id: '10', posicion: 'Inferior, Soporte', nombre: 'Ashe', precio: convertir(260), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg', biografia: 'Como Hija del Hielo y madre de guerra de la tribu Avarosa, Ashe comanda la más grande horda en el norte. Estoica, inteligente e idealista, pero incómoda con su rol de líder, ella aprovecha las magias ancestrales de su linaje para portar un arco de Hielo Puro. Apoyada por la creencia de su gente que ella es el héroe mitológico reencarnado de Avarosa, Ashe espera unificar el Fréljord una vez más al retomar sus tierras antiguas y tribales.', dificultad: 2 },
    { id: '11', posicion: 'Central', nombre: 'Aurelion Sol', precio: convertir(975), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg', biografia: 'Aurelion Sol alguna vez adornó el gran vacío del cosmos con maravillas celestiales de su propia creación. Ahora, se ve obligado a usar su increíble poder para el beneficio de un imperio espacial que, tras engañarlo, lo mantiene bajo su servicio. Deseoso de volver a sus días de gloria, Aurelion Sol bajaría cada estrella del cielo, si tuviera que hacerlo, con tal de recuperar su libertad.', dificultad: 2 },
    { id: '12', posicion: 'Central', nombre: 'Azir', precio: convertir(880), foto: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg', biografia: 'Azir, emperador de Shurima en un pasado remoto, fue un hombre orgulloso que estuvo a punto de alcanzar la inmortalidad. Dominado por la arrogancia, fue traicionado y asesinado en la hora de su mayor triunfo. Pero ahora, milenios después, renació como un ser Ascendido de inmenso poder. Su enterrada ciudad resurgió de las arenas y Azir está decidido a restaurar la antigua gloria de Shurima.', dificultad: 3 }
];

export const gFetch = new Promise((resolve, reject) => {
    let condition = true;
    if (condition) {
        setTimeout(() => {
            resolve(campeones)
        }, 2000)
    } else {
        reject('404 not found')
    }
})

export const getItems = (id) => new Promise((resolve, reject) => {
    let condition = true;
    if (condition) {
        setTimeout(() => {
            resolve(campeones.find(camp => camp.id === id))
        }, 2000)
    } else {
        reject('404 not found')
    }
})

function convertir(rp) {
    return (rp * 5 / 710).toFixed(2);
}